#!/usr/bin/env python
"""Fine-tune a pretrained ResNet-50 on ESC-50 spectrogram images.

Supports two modes:
1. On-the-fly spectrogram generation via `ESC50SpectrogramDataset` (default).
2. Training on pre-computed PNGs generated by `make_spectrograms.py` (pass
   `--spectrogram_dir`).

Example
-------
python -m RISE_audio.training.fine_tune_resnet \
       --esc50_root ESC50 \
       --epochs 10 \
       --batch_size 32
"""

from __future__ import annotations

import argparse
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import transforms, datasets, models
from tqdm import tqdm
import numpy as np

from utils import (
        ESC50SpectrogramDataset,
        preprocess as default_preprocess,
    )
from sklearn.model_selection import StratifiedKFold


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def parse_args():
    p = argparse.ArgumentParser(description="Fine-tune ResNet-50 on ESC-50")
    p.add_argument("--esc50_root", type=str, required=True, help="Path to ESC-50 dataset root")
    p.add_argument("--spectrogram_dir", type=str, default=None, help="Path to pre-computed PNG directory (ImageFolder style)")
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--batch_size", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--val_split", type=float, default=0.2, help="Fraction for validation if not using predefined folds")
    p.add_argument("--kfolds", type=int, default=5, help="Number of folds for cross-validation; if 1 behaves like normal train/val split")
    p.add_argument("--out_checkpoint", type=str, default="resnet50_esc50_fold{fold}.pt", help="Pattern for checkpoint filenames. Use {fold} placeholder.")
    p.add_argument("--num_workers", type=int, default=4)
    return p.parse_args()


def yield_folds(args):
    """Generator that yields (train_dataset, val_dataset, fold_id) tuples."""
    if args.spectrogram_dir is not None:
        preprocess = transforms.Compose(
            [
                transforms.Resize((224, 224)),
                transforms.Grayscale(num_output_channels=3),
                transforms.ToTensor(),
                transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
            ]
        )
        full_ds = datasets.ImageFolder(args.spectrogram_dir, transform=preprocess)
        targets = np.array(full_ds.targets)

        if args.kfolds <= 1:
            # Single split (random)
            val_len = int(len(full_ds) * args.val_split)
            train_len = len(full_ds) - val_len
            train_ds, val_ds = random_split(full_ds, [train_len, val_len])
            yield train_ds, val_ds, 0
        else:
            if StratifiedKFold is None:
                raise ImportError("scikit-learn is required for K-fold CV on pre-computed images")
            skf = StratifiedKFold(n_splits=args.kfolds, shuffle=True, random_state=42)
            for fold_id, (train_idx, val_idx) in enumerate(skf.split(np.zeros(len(targets)), targets), 1):
                train_ds = torch.utils.data.Subset(full_ds, train_idx)
                val_ds = torch.utils.data.Subset(full_ds, val_idx)
                yield train_ds, val_ds, fold_id
    else:
        full_ds = ESC50SpectrogramDataset(args.esc50_root, transform=default_preprocess)
        if args.kfolds <= 1:
            # Default ESC-50 split (fold 5 as val)
            train_idx = [i for i, f in enumerate(full_ds.df["fold"]) if f != 5]
            val_idx = [i for i, f in enumerate(full_ds.df["fold"]) if f == 5]
            yield torch.utils.data.Subset(full_ds, train_idx), torch.utils.data.Subset(full_ds, val_idx), 5
        else:
            # Use official ESC-50 5-fold cross-validation (fold values 1-5)
            for fold_id in range(1, 6):
                train_idx = [i for i, f in enumerate(full_ds.df["fold"]) if f != fold_id]
                val_idx = [i for i, f in enumerate(full_ds.df["fold"]) if f == fold_id]
                yield torch.utils.data.Subset(full_ds, train_idx), torch.utils.data.Subset(full_ds, val_idx), fold_id


def train(model, loader, criterion, optimizer):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for x, y in tqdm(loader, desc="Train", leave=False):
        x, y = x.to(DEVICE), y.to(DEVICE)
        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * x.size(0)
        _, pred = out.max(1)
        correct += pred.eq(y).sum().item()
        total += x.size(0)
    return running_loss / total, correct / total


def validate(model, loader, criterion):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for x, y in tqdm(loader, desc="Val", leave=False):
            x, y = x.to(DEVICE), y.to(DEVICE)
            out = model(x)
            loss = criterion(out, y)
            running_loss += loss.item() * x.size(0)
            _, pred = out.max(1)
            correct += pred.eq(y).sum().item()
            total += x.size(0)
    return running_loss / total, correct / total


def main():
    args = parse_args()

    fold_acc = []
    for train_ds, val_ds, fold_id in yield_folds(args):
        print(f"\n===== Fold {fold_id}/{args.kfolds if args.kfolds>1 else 'N/A'} =====")

        train_loader = DataLoader(
            train_ds,
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.num_workers,
            pin_memory=True,
        )
        val_loader = DataLoader(
            val_ds,
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=True,
        )

        model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
        model.fc = nn.Linear(model.fc.in_features, 50)
        model.to(DEVICE)

        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=args.lr)

        best_acc = 0.0
        for epoch in range(1, args.epochs + 1):
            tr_loss, tr_acc = train(model, train_loader, criterion, optimizer)
            val_loss, val_acc = validate(model, val_loader, criterion)
            print(
                f"Fold {fold_id} | Epoch {epoch:02d}/{args.epochs} | "
                f"Train {tr_acc:.3f} | Val {val_acc:.3f}"
            )
            if val_acc > best_acc:
                best_acc = val_acc
                ckpt_path = args.out_checkpoint.format(fold=fold_id)
                torch.save(model.state_dict(), ckpt_path)
                print(f"  [*] New best checkpoint: {ckpt_path}")

        fold_acc.append(best_acc)
        print(f"Fold {fold_id} best val acc: {best_acc:.3f}")

    if len(fold_acc) > 1:
        print("\n===== Cross-validation summary =====")
        for i, acc in enumerate(fold_acc, 1):
            print(f"Fold {i}: {acc:.3f}")
        print(f"Mean accuracy: {np.mean(fold_acc):.3f} ± {np.std(fold_acc):.3f}")


if __name__ == "__main__":
    main() 